image: atlassian/docker-release-maker:latest

pipelines:
  custom:
    base-8-create-releases:
      - step:
          services:
            - docker
          script:
            - export BASE_VERSION='8'
            - export CONCURRENT_BUILDS='4'
            - export DEFAULT_RELEASE='true'
            - export DOCKER_REPO='dchevell/jira-software'
            - export DOCKERFILE_VERSION_ARG='JIRA_VERSION'
            - export MAC_PRODUCT_KEY='jira-software'
            - export TAG_SUFFIXES='jdk8,ubuntu'
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - python /usr/src/app/run.py --create
    base-8-create-custom-release:
      - variables:
          - name: JIRA_VERSION
          - name: DOCKER_TAG
      - step:
          services:
            - docker
          script:
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - docker build -t dchevell/jira-software:${DOCKER_TAG} --build-arg JIRA_VERSION=${JIRA_VERSION} .
            - docker push dchevell/jira-software:${DOCKER_TAG}
  branches:
    base-8:
      - step:
          services:
            - docker
          script:
            - export BASE_VERSION='8'
            - export CONCURRENT_BUILDS='4'
            - export DEFAULT_RELEASE='true'
            - export DOCKER_REPO='dchevell/jira-software'
            - export DOCKERFILE_VERSION_ARG='JIRA_VERSION'
            - export MAC_PRODUCT_KEY='jira-software'
            - export TAG_SUFFIXES='jdk8,ubuntu'
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - python /usr/src/app/run.py --update