image: atlassian/docker-release-maker:latest

pipelines:
  custom:
    create-release-base-8:
      - step:
          services:
            - docker
          script:
            - export BASE_VERSION='8'
            - export DEFAULT_RELEASE='true'
            - export DOCKER_REPO='dchevell/jira-software'
            - export DOCKERFILE_VERSION_ARG='JIRA_VERSION'
            - export MAC_PRODUCT_KEY='jira-software'
            - export TAG_SUFFIXES='jdk8,ubuntu'
            - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
            - python /usr/src/app/run.py --create
  branches:
    base-8:
      - step:
          services:
            - docker
          script:
            - export BASE_VERSION='8'
            - export DEFAULT_RELEASE='true'
            - export DOCKER_REPO='dchevell/jira-software'
            - export DOCKERFILE_VERSION_ARG='JIRA_VERSION'
            - export MAC_PRODUCT_KEY='jira-software'
            - export TAG_SUFFIXES='jdk8,ubuntu'
            - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
            - python /usr/src/app/run.py --update