version: '3.5'

services:
  postgresql:
    image: postgres:9.6-alpine
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=jira'
      - 'POSTGRES_USER=jiradb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
      - "LANG=C"

  jira:
    build:
      context: .
      args:
        - JIRA_VERSION
    depends_on:
      - postgresql
    ports:
      - '2990:8080'
      - '5005:5005'
    environment:
      - 'ATL_JDBC_URL=jdbc:postgresql://postgresql/jira'
      - 'ATL_JDBC_USER=jiradb'
      - 'ATL_JDBC_PASSWORD=password'
      - 'ATL_DB_DRIVER=org.postgresql.Driver'
      - 'ATL_DB_TYPE=postgres72'
      - 'ATL_TOMCAT_CONTEXTPATH=/jira'
    command: >
      bash -c '
          /opt/atlassian/support/waitport postgresql 5432 &&
          chown -R jira.jira  /var/atlassian/application-data/jira/ &&
          /entrypoint.py
      '

  smoketests:
    build:
      context: ./smoketest-image/
    environment:
      - 'JIRA_BASE_URL=http://jira:8080/jira'
      - 'JIRA_ADMIN='
      - 'JIRA_ADMIN_PWD=admin'
      - 'JIRA_USER=user'
      - 'JIRA_USER_PWD=password'
    command: >
      bash -c '
          sleep 1000000
      '
